export const EX_LINKS: Record<string, string> = {
  "1-Arm 45° Cable Rear Delt Flye": "https://youtu.be/6G5DmVaocGM",
  "45° Hyperextension": "https://youtu.be/lEeCPhlFZig?si=j-525U0GRL6YMLvK",
  "45° Incline Barbell Press": "https://youtu.be/vqQ9ok0dEgk",
  "45° Incline DB Press": "https://www.youtube.com/watch?v=p2t9daxLpB8",
  "45° Incline Machine Press": "https://youtu.be/b8fYnZ-usP0",
  "Ab Wheel Rollout": "https://youtu.be/gGTgyCU9gcg?si=2h_43OzMnRo5nVWU",
  "Arm Circles": "https://youtu.be/tFpwBr_7KPg?si=ZBn0o9wo6P78IwIg&t=10",
  "Arm Swings": "https://youtu.be/tFpwBr_7KPg?si=-dwT-qM4TzVqRWGx",
  "Barbell Bench Press": "https://youtu.be/nQL5ieH39sw?si=RjZSWBZ3CGKg-pax",
  "Barbell RDL": "https://youtu.be/3fJwfg51cv0",
  "Bayesian Cable Curl": "https://youtu.be/CWH5J_7kzjM?si=FlPzreLDPHogRxve",
  "Bench Dip": "https://youtu.be/3CaIq8jZe18?si=ZWFiM0R-hqcvpiQj",
  "Bottom-Half DB Flye": "https://youtu.be/qJzc-iHKGdg?si=GGd61Dr4uoDUI9b6",
  "Bottom-Half Seated Cable Flye": "https://youtu.be/tsJMV9Gxw-o?si=RBV8vCl6CNAx22eD",
  "Cable Crossover Ladder": "https://youtu.be/0TP9kVcWGic?si=5lWdSFfUA27mop9-",
  "Cable Crunch": "https://youtu.be/epBrpaGHMcg?si=FMV9IKBOvBkuUOZM",
  "Cable External Rotation (optional)": "https://youtu.be/tFpwBr_7KPg?si=ui18pgNWTE2IrKcu&t=39",
  "Cable Hip Abduction": "https://youtu.be/552L1K3Rb_Q?si=bwLZLzHR0AHulO9I",
  "Cable Paused Shrug-In": "https://youtu.be/Hy6f1Lz_PiA?si=MTEbKv_uMCL6zvge",
  "Cable Pull-Through": "https://youtu.be/eFsNZc69m10?si=HeWumPVqClmv0LyC",
  "Cable Rope Hammer Curl": "https://youtu.be/TTgICSfj1hY?si=yOoxlJpIv6HqFkwW",
  "Cable Shoulder Press": "https://youtu.be/OfjncdW_Vyc?si=kiSMQzlVHKNIQJ7J",
  "Cable Triceps Kickback": "https://youtu.be/oRxTKRtP8RE?si=S_C_5SZAal_SIFBq",
  "Chest-Supported Machine Row": "https://youtu.be/ijsSiWSzYw0?si=ADBJRkNSajLiVayN",
  "Chest-Supported T-Bar Row": "https://youtu.be/q8qlHwcuOtc?si=J-TyFYuv9rwi5VTy",
  "Concentration Cable Curl": "https://youtu.be/BFZyW_7ld0c?si=2quAznmV1D3pvYGG",
  "DB Bench Press": "https://youtu.be/zGXvPjlgVkk?si=sTJq1mF8qaCapYbx",
  "DB Bulgarian Split Squat": "https://youtu.be/htDXu61MPio?si=WNsXh0BmNMXONRHP",
  "DB Concentration Curl": "https://youtu.be/Oq7gJuAuJh0?si=MVr0h6JsUR4PxMgw",
  "DB Curl": "https://youtu.be/XxGCRSJmgwY?si=4ohHVIRqih3xCbD0",
  "DB Hammer Curl": "https://youtu.be/xY3sQXYhk7A?si=DPCD_x4ApcM8y3uN",
  "DB Preacher Curl": "https://youtu.be/WTkQLAethtg?si=BRKYwVgqPyD9Iayw",
  "DB RDL": "https://youtu.be/VRwSgUoj7uI",
  "DB Shrug": "https://youtu.be/moFqLlptX7Q?si=vsQXeROXKVa3beB7",
  "DB Skull Crusher": "https://youtu.be/fbLTzgTKOR8?si=z-O6SNR4HG4rd09j",
  "DB Static Lunge": "https://youtu.be/hci6iKFtTkg?si=R8PHuNMWbGOoTd9e",
  "DB Step-Up": "https://youtu.be/3FNfi_PrP9Y?si=xHZ-SXqhL_0_tXBD",
  "DB Triceps Kickback": "https://youtu.be/YdUUYFgpA7g?si=IiD6eODwVqDS3WlB",
  "DB Walking Lunge": "https://youtu.be/BC_eDtrB-M4?si=lhut9GRQ9n9g82Mz",
  "Decline Weighted Crunch": "https://youtu.be/ZheUsKqU81M?si=r3a6FT_AqWp1nq6L",
  "Dual-Handle Lat Pulldown": "https://youtu.be/NwQ5Ch5t5Vk?si=JHztlva6LI2NPBDC",
  "EZ-Bar Cable Curl": "https://youtu.be/ck1zjNTnFew?si=EgggtiVFxulCoYXU",
  "EZ-Bar Curl": "https://youtu.be/WMrgn4GG7mI?si=0dUmQt-g_zOMm14G",
  "EZ-Bar Preacher Curl": "https://youtu.be/Dn7qgf9iSH8?si=mCWsykyTRl0jYKA0",
  "EZ-Bar Skull Crusher": "https://youtu.be/oDKGCsTjAk8?si=6CA3mVlk1fYWb8Ek",
  "Front-to-Back Leg Swings": "https://youtu.be/tFpwBr_7KPg?si=xiy3TjoRiQUvn7qX&t=19",
  "Glute-Ham Raise": "https://youtu.be/9ksG-O0ZUto?si=I5F9HRiZe4C8JNOo",
  "Goblet Squat": "https://youtu.be/S2agsLlUSII?si=ZbM6zqY3sC151i0A",
  "Hack Squat": "https://youtu.be/TWUnnDK8rck?si=NmqKbwgMcHmaDp6T",
  "Hammer Preacher Curl": "https://youtu.be/dEdnC3ca-Yg?si=fAVE3jH_TAGmtG_u",
  "Hanging Leg Raise": "https://youtu.be/rGqwkinWqYI?si=-ygKr5ZOwrYdG0fX",
  "High-Bar Back Squat": "https://youtu.be/V-B_Y-OvOTQ?si=3cSY6hI1IDiedc8y",
  "High-Cable Cuffed Lateral Raise": "https://youtu.be/8m2jNHBP580?si=a4KGz2Dm0gRioyBG",
  "High-Cable Lateral Raise": "https://youtu.be/MnMux3Wc0Ac?si=diOk1ZKwTwTa4Sx0",
  "Incline Chest-Supported DB Row": "https://youtu.be/okCWuhxJEvw?si=-Q9-BAJbFeebhfpF",
  "Incline DB Stretch Curl": "https://youtu.be/Z0NIYS9nyoQ?si=PgrGaJLln2uZLfnY",
  "Katana Triceps Extension": "https://youtu.be/R7f45Mv7yyg?si=xsSbcMbkSOuYetpO",
  "Lateral Band Walk": "https://youtu.be/sOYvvFPYdsU?si=QAdyWBV_5NAX2CtW",
  "Lean-Back Lat Pulldown": "https://youtu.be/Zjzt4MRbAlc?si=Z5K9MxycnTyrnB1N",
  "Lean-Back Machine Pulldown": "https://youtu.be/CrfvmSGfT2c?si=hsWBdUyeIyjzr_7h",
  "Lean-Back Pull-Up": "https://youtu.be/Zjzt4MRbAlc?si=Z5K9MxycnTyrnB1N",
  "Lean-In DB Lateral Raise": "https://youtu.be/BmYuAG2j2co",
  "Leg Extension": "https://youtu.be/uFbNtqP966A?si=3mIG7OVH30gHjNhd",
  "Leg Press": "https://youtu.be/1yKAQLVV_XI?si=G0wEZEbz8Kq9vFnF",
  "Leg Press Calf Press": "https://youtu.be/S6DTPNZ_-F4?si=y3rx6TaVEuUONiI2",
  "Long-Lever Plank": "https://youtu.be/9rFS1gg0vJM?si=ihh3GBLwr9TyBojo",
  "Low-to-High Cable Crossover": "https://youtu.be/1LhGmhVFe2Y?si=vTZPhYePzGkU4I-g",
  "Lying Leg Curl": "https://youtu.be/sX4tGtcc62k?si=mparE5f2nb9KfXPl",
  "Lying Leg Raise": "https://youtu.be/w86Ph4iQgBM?si=IihE5X5en99z1H82",
  "Machine Chest Press": "https://youtu.be/zDecGJLyVm8?si=VF-70ajNWU4cDHEV",
  "Machine Crunch": "https://youtu.be/K2yKEoazT3g?si=mLbXtOh8oUF8lcIs",
  "Machine Hip Abduction": "https://youtu.be/pozooPg6PBE?si=uVtC8JPKXvZKeVlE",
  "Machine Preacher Curl": "https://youtu.be/R2iUnBxFtis",
  "Machine Shoulder Press": "https://youtu.be/SCQVmN1gYsk?si=Enyh4L6ZDiCc6RyU",
  "Machine Shrug": "https://youtu.be/ua0XuKwKQ9M?si=Y-kGNEq_riqAF2Tn",
  "Modified Candlestick": "https://youtu.be/-XVRl8KU7x0?si=o46w1tp8fNYfD-gU",
  "Neutral-Grip Lat Pulldown": "https://youtu.be/lA4_1F9EAFU?si=5Bh19rDwBplX5QUz",
  "Neutral-Grip Pull-Up": "https://youtu.be/b0ypSz63UGo?si=dMxuJGtxkR4jnUbb",
  "Nordic Ham Curl": "https://youtu.be/fzpYiRtzmFA?si=M3BGSywSskWqGRnE",
  "Overhead Cable Triceps Extension (Bar)": "https://youtu.be/9_I1PqZAjdA?si=hLmz2aLH05YfsUTF",
  "Overhead Cable Triceps Extension (Rope)": "https://youtu.be/GYoUoVNlbGc?si=mKlJH3mz_e7-RCu0",
  "Pec Deck": "https://youtu.be/CI88L1VNvEs?si=UjPZ3Ep5QaYBM5rC",
  "Pendlay Deficit Row": "https://youtu.be/MmuyHKYCLps?si=JK1d5szj5PIIbYYm",
  "Pull-Up": "https://youtu.be/5h_NehuTqe4?si=bZWK6q3A9wnD8TIW",
  "Reverse Nordic": "https://youtu.be/D-kqUKEQZZ0?si=1i2hWkoG06CDuFmq",
  "Reverse Pec Deck": "https://youtu.be/Y8fb_rtEU_4?si=nwaICiwwS3TatSq1",
  "Rope Face Pull": "https://youtu.be/GhrVM-jPIEA?si=_qGmAZLOCDUWVHy_",
  "Seated Calf Raise": "https://youtu.be/6pfj0G7VKdM?si=bXJmuLkyC3E3PYHW",
  "Seated DB Shoulder Press": "https://youtu.be/B8PB5RPhTWQ?si=JQ8J3qbCDkUCGtt5",
  "Seated Leg Curl": "https://youtu.be/yv0aAY7M1mk?si=Z1Cx7ih-vWTSTqq-",
  "Seated Super-Bayesian High Cable Curl": "https://youtu.be/jQ9rkfvAbIc?si=m1Q5OHGTNvhD6TZ9",
  "Side-to-Side Leg Swings": "https://youtu.be/tFpwBr_7KPg?si=m5M3W6evtbwi9amN&t=28",
  "Single-Arm DB Row": "https://youtu.be/roKtfQZbxzg?si=x0BVOCTXzrksYhHL",
  "Sissy Squat": "https://youtu.be/eWAjlO4FWPQ?si=CaRzMpTB37IdGgpM",
  "Smith Machine Row": "https://youtu.be/Wmivm40AV3Q?si=pAcxmzGxP16bt5I5",
  "Smith Machine Squat": "https://youtu.be/J2D2J7RO_tA",
  "Smith Machine Static Lunge": "https://youtu.be/SEjKxJGg_C8?si=I_mi9RO4vFVVhFER",
  "Smith Machine Static Lunge w/ Elevated Front Foot": "https://youtu.be/GOqHdmshRKY",
  "Snatch-Grip RDL": "https://youtu.be/b8fmEaXHapU",
  "Standing Calf Raise": "https://youtu.be/6lR2JdxUh7w?si=Q_4oyceNkI-WarRg",
  "Swiss Ball Rollout": "https://youtu.be/FvekMyIs-yk?si=WE_SAmFUUdmsWGgL",
  "Triceps Pressdown (Bar)": "https://youtu.be/o4eazahiXQw?si=L61XPqSVKpnjf1r1",
  "Triceps Pressdown (Rope)": "https://youtu.be/bCa036rGtVU?si=egxwlHADiCBQGss7",
  "Walking Lunge": "https://youtu.be/BC_eDtrB-M4?si=j6tHLEbqdJRbGeTW",
  "Wide-Grip Lat Pulldown": "https://youtu.be/IYXRrYXfVLc?si=8eUNzIQ9o7Y-XpSp",
  "Wide-Grip Pull-Up": "https://youtu.be/yGnp0HU8BnA?si=g9lS7YfxwnBQ5gbR",
};
